import turtle as t

def draw_table():
    #table top
    t.fillcolor("blue")
    t.begin_fill()
    t.penup()
    t.goto(-100, 50)  
    t.pendown()
    t.forward(200)    
    t.right(90)
    t.forward(20)    
    t.right(90)
    t.forward(200)   
    t.right(90)
    t.forward(20)     
    t.right(90) 
    t.end_fill()
    t.penup()
    t.goto(-90, 30)
    
    #legs
    t.up()
    t.right(90)
    t.down()
    t.forward(80)
    t.left(90)
    t.up()
    t.forward(40)
    t.left(90)
    t.forward(20)
    t.down()
    t.forward(60)
    t.up()
    t.right(90)
    t.forward(100)
    t.right(90)
    t.down()
    t.forward(60)
    t.up()
    t.forward(20)
    t.left(90)
    t.forward(40)
    t.down()
    t.left(90)
    t.forward(80)
draw_table()
t.exitonclick()